name: deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SWIFT_WASM: swift-wasm-6.1-RELEASE
    steps:
      - uses: actions/checkout@v4

      - name: Install Packages
        run: >
          sudo apt-get update &&
          sudo apt-get install -y
          git libcurl4-openssl-dev libedit2 libgcc-9-dev
          libpython3.8 libsqlite3-0 libstdc++-9-dev libxml2-dev libz3-dev
          zlib1g-dev binaryen

      - name: Download Swift
        run: |
          curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz && \
            tar zxf swiftly-$(uname -m).tar.gz && \
            ./swiftly init --quiet-shell-followup && \
            . "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh" && \
            hash -r
        working-directory: /home/runner

      - run: tar xzf ${{ env.SWIFT }}-ubuntu22.04.tar.gz
        working-directory: /home/runner
      - run: echo /home/runner/${{ env.SWIFT }}-ubuntu22.04/usr/bin >> ${GITHUB_PATH}
      - run: swift --version

      - name: Install Wasm SDK
        run: swift sdk install https://github.com/swiftwasm/swift/releases/download/${{ env.SWIFT_WASM }}/${{ env.SWIFT_WASM }}-wasm32-unknown-wasi.artifactbundle.zip
  
      - name: Build Swift
        run: bin/build

      - run: npm install
      - run: npm run build -- --base=/swift-string-counter-web/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/deploy-pages@v4
